---
applications:
- name: hello-v1
  memory: 64M
  instances: 1
  hosts: 
  - hello-ns
  - hello-v1
  buildpack: php_buildpack
  path: hello-v1/
- name: hello-v2
  memory: 64M
  instances: 1
  host: hello-v2
  buildpack: php_buildpack
  path: hello-v2/
